import type { Credential } from "@/lib/types";

const drive = (id: string) => `https://drive.google.com/file/d/${id}/view`;
const landscape = (name: string, height = 990) => ({
  src: `/images/certificates/${name}.jpg`,
  width: 1400,
  height,
});

export const credentials: Credential[] = [
  {
    title: "Data Analysis & Visualization",
    issuer: "3MTT · NITDA",
    partner: "SAIL Innovation Lab",
    date: "20 May 2024",
    isoDate: "2024-05-20",
    group: "Data",
    description:
      "Online and physical applied learning in the 3 Million Technical Talent programme.",
    reference: { label: "Fellow ID", value: "FE/23/43936560" },
    image: { src: "/images/certificates/3mtt-data-analysis-visualization.jpg", width: 990, height: 1400 },
    original: drive("105sgQ2dFoiL72YlC0mwOOpMif-CsA7ZA"),
  },
  {
    title: "Data Science & Analytics",
    issuer: "HP LIFE · HP Foundation",
    date: "26 Sep 2024",
    isoDate: "2024-09-26",
    group: "Data",
    description:
      "Data science and analytics practices, methodologies and tools, and the benefits and challenges of a data-driven approach.",
    image: landscape("hp-life-data-science-analytics", 1082),
    original: drive("1UlhXOTfqyStK0yIX97JlymmOJkdLfyo8"),
  },
  {
    title: "Presenting Data",
    issuer: "HP LIFE · HP Foundation",
    date: "27 Sep 2024",
    isoDate: "2024-09-27",
    group: "Data",
    description:
      "Creating effective charts in spreadsheet software and choosing the right chart to convey information.",
    reference: { label: "Serial", value: "07e768f8-86de-49fe-b6ad-af8efc12a48c" },
    image: landscape("hp-life-presenting-data"),
    original: drive("1fg9oNZY39yl-Nd3eSCRZnCFh9C1KmuRA"),
  },
  {
    title: "Essentials of Data Visualization using MS Excel",
    issuer: "UniAthena",
    partner: "Acacia University Professional Development",
    date: "21 Sep 2024",
    isoDate: "2024-09-21",
    group: "Data",
    description: "Blockchain-verified certificate; scan the QR code on the certificate to verify.",
    reference: { label: "Blockchain ID", value: "8533-6645-7017" },
    image: landscape("uniathena-data-visualization-excel", 944),
    original: drive("1Kg5AcbvOXUBiQXG4iX5c0F5KzDfMZtO7"),
  },
  {
    title: "Essentials of MS Excel: Formulas and Functions",
    issuer: "UniAthena",
    partner: "Cambridge International Qualifications, UK",
    date: "21 Sep 2024",
    isoDate: "2024-09-21",
    group: "Data",
    description: "Blockchain-verified certificate; scan the QR code on the certificate to verify.",
    reference: { label: "Blockchain ID", value: "5195-5826-5971" },
    image: landscape("uniathena-excel-formulas-functions", 944),
    original: drive("1NB3Bq6v4Y_Kgz-P945UrqPrx6r044nBu"),
  },
  {
    title: "Basics of Data Science",
    issuer: "UniAthena",
    partner: "Cambridge International Qualifications, UK",
    date: "21 Sep 2024",
    isoDate: "2024-09-21",
    group: "Data",
    description: "Blockchain-verified certificate; scan the QR code on the certificate to verify.",
    reference: { label: "Blockchain ID", value: "4571-1523-7276" },
    image: landscape("uniathena-basics-of-data-science", 944),
    original: drive("18ywOusgz_AwFf9nbpS6C3k9XaiFz8XPk"),
  },
  {
    title: "Basics of Python",
    issuer: "UniAthena",
    partner: "Cambridge International Qualifications, UK",
    date: "20 Sep 2024",
    isoDate: "2024-09-20",
    group: "Data",
    description: "Blockchain-verified certificate; scan the QR code on the certificate to verify.",
    reference: { label: "Blockchain ID", value: "8306-8450-3385" },
    image: landscape("uniathena-basics-of-python", 944),
    original: drive("1KAYtnx2t7oB-vGZ2D-kKNINnDpLhUOrK"),
  },
  {
    title: "Effective Presentations",
    issuer: "HP LIFE · HP Foundation",
    date: "28 Sep 2024",
    isoDate: "2024-09-28",
    group: "Professional skills",
    description: "Tailoring information to an audience and designing persuasive presentations.",
    reference: { label: "Serial", value: "d6d21491-73f0-45f8-a4a2-4d14f7d0fd55" },
    image: landscape("hp-life-effective-presentations"),
    original: drive("1AZYLcEESw6hEIWA6AXcHVXWRywQd1_Az"),
  },
  {
    title: "Effective Leadership",
    issuer: "HP LIFE · HP Foundation",
    date: "29 Sep 2024",
    isoDate: "2024-09-29",
    group: "Professional skills",
    description: "Leadership strategies and the role of ethics in effective leadership.",
    reference: { label: "Serial", value: "79d0af85-e5ea-4e8b-aff0-098aa07fea83" },
    image: landscape("hp-life-effective-leadership"),
    original: drive("1HzFnDrQnuLQvqnhSKaQWEzjzJgs_bteq"),
  },
  {
    title: "Introduction to Cybersecurity Awareness",
    issuer: "HP LIFE · HP Foundation",
    date: "29 Sep 2024",
    isoDate: "2024-09-29",
    group: "Professional skills",
    description: "Common cybersecurity threats and basic ways to keep online data secure.",
    reference: { label: "Serial", value: "9a00afcd-2586-4c51-9dc1-6e8e2a117cb9" },
    image: landscape("hp-life-cybersecurity-awareness"),
    original: drive("13kzRJYBq5zkpMBjNoNa9y7-yLuXak_4x"),
  },
  {
    title: "Resume Writing and Job Interviewing",
    issuer: "HP LIFE · HP Foundation",
    date: "26 Sep 2024",
    isoDate: "2024-09-26",
    group: "Professional skills",
    description: "Tailored resumes and cover letters, interview preparation and self-assessment.",
    reference: { label: "Serial", value: "1d196e67-a843-4c6b-b413-d06678e96a9d" },
    image: landscape("hp-life-resume-writing"),
    original: drive("1vnZGbGzqgw__Wc6ybtWn7Yov0j0vnAHL"),
  },
];

export const certificationsFolder =
  "https://drive.google.com/drive/folders/1OH6RpN_Y-vlGMIbVQI4ZaG1_Q2Da3lyY";
